import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Button from '@material-ui/core/Button'
import { RichText } from 'prismic-reactjs';

import { Client, manageLocal } from 'Domain/common/utils/prismicHelpers';
import styles from '../styles/Home.module.scss'
import Layout, { siteTitle } from '../components/layout'
import utilStyles from '../styles/utils.module.scss'
import { getSortedPostsData } from '../lib/posts'
import Date from '../components/date'
import { SliceZone } from 'Domain/components'


export default function Home({ allPostsData, doc }) {
  console.log(doc);
  return (
    <Layout home>
      <Head>
        <title>{siteTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <h1>Prismic Spike</h1>
        {RichText.render(doc.data.display_title || [])}
        <SliceZone sliceZone={doc.data.body} />
      </section>
      <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
        <h2 className={utilStyles.headingLg}>Blog</h2>
        <ul className={utilStyles.list}>
          {allPostsData.map(({ id, date, title }) => (
            <li className={utilStyles.listItem} key={id}>
              <Link href={`/posts/${id}`}>
                <a>{title}</a>
              </Link>
              <br />
              <small className={utilStyles.lightText}>
                <Date dateString={date} />
              </small>
            </li>
          ))}
        </ul>
      </section>
      <section className={utilStyles.headingMd}>
        <p>[Your Self Introduction]</p>
        <p>
          (This is a sample website - you’ll be building a site like this on{' '}
          <a href="https://nextjs.org/learn">our Next.js tutorial</a>.)
        </p>
      </section>
      <section className={styles.container}>

        <main className={styles.main}>
          {/* Linkear componentes */}
          <h1 className="title">
            Read{' '}
            <Link href="/posts/first-post">
              <a>this page!</a>
            </Link>
          </h1>
          <Button variant="contained" color="primary">
            Hello World
          </Button>

          <Image
            src="/gab.jpeg" // Route of the image file
            height={240} // Desired size with correct aspect ratio
            width={160} // Desired size with correct aspect ratio
            alt="Your Name"
          />
          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.js</code>
          </p>

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/master/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </section>
    </Layout>


  )
}

// Next, we’ll create a simple library for fetching data from the file system.

export async function getStaticProps({
  locale,
  locales,
}) {
  // these two are optional at the moment
  const ref = null
  const isPreview = false
  // --END---
  locale = locale !== "es-co" ? "es-co" : locale;

  const client = Client();
  const doc =
    (await client.getSingle('homepage', ref ? { ref, lang: locale } : { lang: locale })) ||
    {};
  const allPostsData = getSortedPostsData()
  const { currentLang, isMyMainLanguage } = manageLocal(locales, locale)
  return {
    props: {
      allPostsData,
      doc,
      lang: {
        currentLang,
        isMyMainLanguage,
      },
    }
  }
}